// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutrientCalculator;

#nullable disable

namespace NutrientCalculator.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260215231616_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutrientCalculator.Models.MealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("NutrientCalculator.Models.MealProductEntity", b =>
                {
                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("MealId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("MealProducts");
                });

            modelBuilder.Entity("NutrientCalculator.Models.NutrientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Essential")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Norma")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("NutrientType")
                        .HasColumnType("int");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("NutrientCalculator.Models.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("NutrientCalculator.Models.ProductNutrientEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("ProductId", "NutrientId");

                    b.HasIndex("NutrientId");

                    b.ToTable("ProductNutrients");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rations");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationMealEntity", b =>
                {
                    b.Property<Guid>("RationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("RationId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("RationMeals");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationProductEntity", b =>
                {
                    b.Property<Guid>("RationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("RationId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RationProducts");
                });

            modelBuilder.Entity("NutrientCalculator.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutrientCalculator.Models.MealEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.UserEntity", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutrientCalculator.Models.MealProductEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.MealEntity", "Meal")
                        .WithMany("MealProducts")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrientCalculator.Models.ProductEntity", "Product")
                        .WithMany("MealProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutrientCalculator.Models.ProductNutrientEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.NutrientEntity", "Nutrient")
                        .WithMany("ProductNutrients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrientCalculator.Models.ProductEntity", "Product")
                        .WithMany("ProductNutrients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutrient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.UserEntity", "User")
                        .WithMany("Rations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationMealEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.MealEntity", "Meal")
                        .WithMany("RationMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrientCalculator.Models.RationEntity", "Ration")
                        .WithMany("RationMeals")
                        .HasForeignKey("RationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Ration");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationProductEntity", b =>
                {
                    b.HasOne("NutrientCalculator.Models.ProductEntity", "Product")
                        .WithMany("RationProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutrientCalculator.Models.RationEntity", "Ration")
                        .WithMany("RationProducts")
                        .HasForeignKey("RationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Ration");
                });

            modelBuilder.Entity("NutrientCalculator.Models.MealEntity", b =>
                {
                    b.Navigation("MealProducts");

                    b.Navigation("RationMeals");
                });

            modelBuilder.Entity("NutrientCalculator.Models.NutrientEntity", b =>
                {
                    b.Navigation("ProductNutrients");
                });

            modelBuilder.Entity("NutrientCalculator.Models.ProductEntity", b =>
                {
                    b.Navigation("MealProducts");

                    b.Navigation("ProductNutrients");

                    b.Navigation("RationProducts");
                });

            modelBuilder.Entity("NutrientCalculator.Models.RationEntity", b =>
                {
                    b.Navigation("RationMeals");

                    b.Navigation("RationProducts");
                });

            modelBuilder.Entity("NutrientCalculator.Models.UserEntity", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Rations");
                });
#pragma warning restore 612, 618
        }
    }
}
